name: Add bugs to bugs project

on:
  issues:
    types:
      - opened

jobs:
  test-echo:
    runs-on: ubuntu-latest
    name: test echo token
    steps:
      - run: echo "hamada"
      - run: echo " access token is ${{ secrets.AUTOMATION_TOKEN }}"
      
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.AUTOMATION_TOKEN }}
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/sherifelkassaby/projects/1
          github-token: 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
